version: '3'

services:
    light-server:
        image: drakeapps/light-server
        privileged: true
        restart: always
        volumes:
            - ./config/:/usr/src/app/config
        command: "node mqtt.js --mqttHost ${MQTTHOST}"
    
